version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: thesis_rsl_db
    environment:
      POSTGRES_USER: paulo
      POSTGRES_PASSWORD: japon
      POSTGRES_DB: thesis_rsl
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: thesis_rsl_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

